main/urls.py
from django.conf.urls import url

from .views import (
    TestListView,
    TestDescriptionView,
    TestRunView,
    TestScoreView,
)


urlpatterns = [
    url(r'^$', TestListView.as_view(), name='tests'),
    url(r'^test/(?P<pk>[0-9]+)/$', TestDescriptionView.as_view(), name='test_description'),
    url(r'^test_run/(?P<pk>[0-9]+)/$', TestRunView.as_view(), name='test_run'),
    url(r'^test_score/(?P<pk>[0-9]+)/$', TestScoreView.as_view(), name='test_score'),
]

tester/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^', include(('main.urls', 'main'), namespace='main')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    pass


class Test(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    test = models.ForeignKey(Test, related_name='questions', on_delete=models.CASCADE)
    text = models.TextField()
    type = models.CharField(choices=[
            ('text', 'text'),
            ('select', 'select'),
        ],
        max_length=255,
        default='text',
    )

    def __str__(self):
        return self.text


class Answer(models.Model):
    test = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    right = models.BooleanField(default=False)
    value = models.CharField(max_length=255)

    def __str__(self):
        return self.value


class TestRun(models.Model):
    user = models.ForeignKey(User, related_name='test_runs', on_delete=models.CASCADE)
    test = models.ForeignKey(Test, related_name='test_runs', on_delete=models.CASCADE)
    score = models.IntegerField(null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    finish_date = models.DateTimeField(null=True)


class TestRunAnswer(models.Model):
    test_run = models.ForeignKey(TestRun, related_name='answers', on_delete=models.CASCADE)
    question = models.ForeignKey(Question, related_name='+', on_delete=models.CASCADE)
    text = models.CharField(max_length=255, blank=True)
    choice = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)

    class Meta:
        unique_together = ('test_run', 'question')

main/forms.py
from django import forms


class TestForm(forms.Form):
    TEMPLATE_QUESTION_NAME = 'question_%s'

    def __init__(self, questions, *args, **kwargs):
        super(TestForm, self).__init__(*args, **kwargs)
        for question in questions:
            field_name = self.TEMPLATE_QUESTION_NAME % question.pk
            self.fields[field_name] = forms.CharField(label=question.text)

main/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.timezone import now


from main.models import Test, TestRun, TestRunAnswer
from main.forms import TestForm
from main.common.utils import calculate_score

# Create your views here.


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    context_object_name = 'tests'
    template_name = 'tests.html'


class TestDescriptionView(LoginRequiredMixin, DetailView):
    model = Test
    context_object_name = 'test'
    template_name = 'test_description.html'

    def post(self, request, *args, **kwargs):
        test_run = TestRun.objects.create(
            user=request.user,
            test=self.get_object(),
        )
        return redirect(reverse('main:test_run', kwargs={'pk': test_run.pk}))


class TestRunView(LoginRequiredMixin, DetailView):
    model = TestRun
    context_object_name = 'test_run'
    template_name = 'test_run.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        questions = self.object.test.questions.all()
        context['form'] = TestForm(questions)
        return context

    def post(self, request, *args, **kwargs):
        test_run = self.get_object()
        questions = test_run.test.questions.all()
        form = TestForm(questions, request.POST)
        if form.is_valid():
            score = calculate_score(form.cleaned_data, questions, test_run)
            test_run.score = score
            test_run.finish_date = now()
            test_run.save(update_fields=['score', 'finish_date'])
            return redirect(reverse('main:test_score', kwargs={'pk': test_run.pk}))
        return render(request, 'test_run.html', context={
            'test_run': test_run,
            'form': form,
        })


class TestScoreView(LoginRequiredMixin, DetailView):
    model = TestRun
    template_name = 'test_score.html'
    context_object_name = 'test_run'

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Choose test</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content%}
    </div>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/test_description.html
{% extends 'base.html' %}

{% block content %}
    <h3>
        Test - #{{ test.name }}<br>
        Description - {{ test.description }}
    </h3>
<form action="{% url 'main:test_description' test.pk %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <button type="submit" class="btn btn-primary">Start test</button>
    </div>
</form>
{% endblock content %}

main/templates/test_run.html
{% extends 'base.html' %}

{% block content %}
    <h3>
        Test - #{{ test_run.test.name }}<br>
        Description - {{ test_run.test.description }}
    </h3>
<form action="{% url 'main:test_run' test_run.pk %}" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        <p>NOT VALID</p>
        {% for errors in form.errors %}
            {{ errors }}
        {% endfor %}
    {% endif %}
    {{ form.as_table }}
    <div class="row">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock content %}

main/templates/test_score.html
{% extends 'base.html' %}

{% block content %}
    <h1>Score</h1>
    Test run pk - {{ test_run.pk }}<br>
    Test score - {{ test_run.score }}
{% endblock content %}

main/templates/tests.html
{% extends 'base.html' %}

{% block content %}
    {% for test in tests %}
        <a href="{% url 'main:test_description' test.pk %}">
            <div class="row">
                <div class="col-md-1">
                    {{ test.pk }}
                </div>
                <div class="col-md-6">
                    {{ test.name }}
                </div>
            </div>
        </a>
    {% endfor %}
{% endblock content %}